server:
    port: 80
logging:
    path: /var/log/${spring.application.name}
spring:
    application:
        name: suntion-gateway
        profiles:
            active: ${active.profile}
    cloud:
        gateway:
            routes:
            -   id: suntion-sms
                uri: lb://suntion-sms
                predicates:
                - Path=/sms/**
            -   id: suntion-auth
                uri: lb://suntion-auth
                predicates:
                - Path=/auth/**
            discovery:
                locator:
                    lowerCaseServiceId: true
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8761/eureka
