server:
    port: 80
spring:
    application:
        name: suntion-gateway
    cloud:
        gateway:
            routes:
            -   id: suntion-sms
                uri: lb://suntion-sms
                predicates:
                - Path=/sms/**
            -   id: suntion-auth
                uri: lb://suntion-auth
                predicates:
                - Path=/auth/**
            discovery:
                locator:
                    lowerCaseServiceId: true
eureka:
    client:
        service-url:
            defaultZone: http://http://47.106.122.50:8101/eureka
