server:
    port: 8101
spring:
    application:
        name: suntion-eureka
eureka:
    instance:
        hostname: suntion.cc
    client:
        register-with-eureka: false
        fetch-registry: false
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 10000
