server:
    port: 8761
spring:
    application:
        name: eureka-cluster
    profiles:
        active: ${active.profile}
eureka:
    instance:
        hostname: eureka-server
    client:
        service-url:
            - http://127.0.0.1:8762/eureka/

