server:
    port: 8762
eureka:
    instance:
        hostname: eureka-server-1
        prefer-ip-address: true
        instance-id: ${spring.cloud.client.ipAddress}:${server.port}
        leaseRenewalIntervalInSeconds: 10 #续约更新
        leaseExpirationDurationInSeconds: 30 #续约到期
    client:
        # 表示是否注册自身到eureka服务器
        # register-with-eureka: false
        # 是否从eureka上获取注册信息
        # fetch-registry: false
        service-url:
            defaultZone: http://localhost:8761/eureka/
