server:
    port: 9001
spring:
    application:
        name: suntion-hystrix
eureka:
    client:
        service-url:
            defaultZone: http://suntion.cc:8101/eureka/
turbine:
    app-config: suntion-sms,suntion-auth
    cluster-name-expression: new String("default")